### ISSUE TITLE
Breaks on ssr

### ISSUE THREAD

**Issue by cco3** [cadgerfeast/vue-konami#4]
https://vuejs.org/v2/guide/ssr.html

```
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules/vue-konami/dist/vue-konami.min.js:1:236)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (assets/js/app.86788c43.js:11898:22)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.module.exports.module.exports (assets/js/app.86788c43.js:9197:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at assets/js/app.86788c43.js:118:18
    at Object.<anonymous> (assets/js/app.86788c43.js:121:10)
```

**Comment by cadgerfeast** [comment]
Hi @cco3,

I did push a new version for `vue-konami`, it know has two builds, a **umd** build and a **cjs** one.
Can you try with the cjs build from `vue-konami@1.0.8` ?

**Comment by cco3** [comment]
Seems to work, thanks!
